datasets:
  input:
    type: file
    path: diseases.json
    source: local
default_model: gpt-4o-mini
operations:
  - type: reduce
    name: get_diseases
    prompt: >-
      You are going to be given many articles. 


      {% for input in inputs %}

      article: {{ input.src }}

      {% endfor %}


      SEARCH THROUGH ALL CONTENT OF THE articles of diseases.

       I want you to provide me the name of the disease which showed up the most within all of the articles. In addition, provide me the symptoms of all the diseases mentioned, and rank which one is the worst.
    fold_batch_size: 5
    fold_prompt: >-
      Update the existing list of diseases and facts based on the additional articles content

      {% for input in inputs %}

      article: {{ input.src }}

      {% endfor %}

      Update the existing list with the proper count and name of each disease; if a new disease is seen, add it to the list;  Repeating disease names in the list is allowed, please do it.


      Existing list of fruit/veggie names:
      data: {{ output.diseases, output.symptoms  }}

    output:
      schema:
        symptoms: "list[{disease_name:string, symptoms: list[str]}]"
        top_disease_mentioned: "str"
        most_harmful_disease: "str"
    reduce_key:
      - _all
    model: gpt-4o-mini
pipeline:
  steps:
    - name: data_processing
      input: input
      operations:
        - get_diseases
  output:
    type: file
    path: results.json
    intermediate_dir: intermediate_results
system_prompt: {}
