datasets:
  biodex_sample:
    path: agenticpreprint/biodex/biodex_sample.json
    type: file
  biodex_terms:
    path: agenticpreprint/biodex/biodex_terms.json
    type: file
default_model: azure/gpt-4o-mini
operations:
- model: azure/gpt-4o-mini
  name: group_reactions
  output:
    schema:
      ranked_conditions: list[string]
  pass_through: true
  prompt: 'Given the following medical article, rank the following conditions in order
    of most confident to least confident that the article is describing the condition:

    {{ inputs[0].fulltext_processed }}


    Conditions: {% for value in inputs %}{{ value.reaction }}{% if not loop.last %},
    {% endif %}{% endfor %}


    There may be conditions described in the article that are not in the list. Do
    not include them in the ranked list. Only focus on the conditions in the list.

    '
  reduce_key:
  - id
  type: reduce
- blocking_conditions:
  - all(word in left['extracted_summary'].lower() for word in right['reaction'].lower().split())
  - all(word in right['reaction'].lower().split() for word in left['extracted_summary'].lower())
  - any(word in right['reaction'].lower().split() for word in left['extracted_summary'].lower().split())
  - any(word in left['extracted_summary'].lower().split() for word in right['reaction'].lower().split())
  - all(word in left['fulltext_processed'].lower() for word in right['reaction'].lower().split())
  blocking_keys:
    left:
    - extracted_summary
    right:
    - reaction
  blocking_threshold: 0.2727
  comparison_prompt: 'Can the following condition be found in the following medical
    article?


    Medical article summary: {{ left.extracted_summary }}


    Condition we are looking for: {{ right.reaction }}


    Determine if {{ right.reaction }} is described in the medical article, considering
    the context and meaning beyond just the presence of individual words.'
  embedding_model: text-embedding-3-small
  limit_comparisons: 12750
  model: azure/gpt-4o-mini
  name: match_reactions
  type: equijoin
- model: azure/gpt-4o-mini
  name: synthesized_extracted_summary_extraction
  output:
    schema:
      extracted_summary: string
  prompt: 'Extract a concise summary of the medical conditions, treatments, and outcomes
    discussed in the following medical article. Focus on any specific diseases, syndromes,
    or reactions mentioned, as well as any significant findings or conclusions related
    to these conditions.


    Medical article: {{ input.fulltext_processed }}'
  type: map
pipeline:
  output:
    path: agenticpreprint/biodex/results/extracted_reactions_docetl.json
    type: file
  steps:
  - input: biodex_sample
    name: synthesized_extracted_summary_extraction
    operations:
    - synthesized_extracted_summary_extraction
  - name: match_reactions
    operations:
    - match_reactions:
        left: synthesized_extracted_summary_extraction
        right: biodex_terms
  - input: match_reactions
    name: group_reactions
    operations:
    - group_reactions
