datasets:
  biodex_sample:
    path: agenticpreprint/biodex/biodex_sample.json
    type: file
  biodex_terms:
    path: agenticpreprint/biodex/biodex_terms.json
    type: file
default_model: azure/gpt-4o-mini
operations:
  - name: group_reactions
    optimize: false
    output:
      schema:
        ranked_conditions: list[string]
    pass_through: true
    prompt:
      "Given the following medical article, rank the following conditions in
      order of most confident to least confident that the article is describing the
      condition:

      {{ inputs[0].fulltext_processed }}


      Conditions: {% for value in inputs %}{{ value.reaction }}{% if not loop.last
      %}, {% endif %}{% endfor %}


      There may be conditions described in the article that are not in the list. Do
      not include them in the ranked list. Only focus on the conditions in the list.

      "
    reduce_key:
      - id
    type: reduce
  - name: match_reactions
    blocking_conditions:
      - all(word in left['fulltext_processed'].lower() for word in right['reaction'].lower().split())
    blocking_keys:
      left:
        - conditions
      right:
        - reaction
    blocking_threshold: 0.5253
    comparison_prompt: |
      Can the following condition be found in the following medical article?
      Medical article: {{ left.fulltext_processed }}

      Condition we are looking for: {{ right.reaction }}

      Determine if {{ right.reaction }} is described in the medical article, considering the context and meaning beyond just the presence of individual words.

    embedding_model: text-embedding-3-small
    type: equijoin
    limit_comparisons: 12250
  - name: synthesized_conditions_extraction
    optimize: false
    output:
      schema:
        conditions: string
    prompt: |
      Extract all medical conditions discussed in the provided medical article: {{ input.fulltext_processed }}. Focus specifically on any unique
      characteristics, diagnostic criteria, or outcomes mentioned in the text. Ensure
      the output is clear and highlights key points related to the medical subject
      of the article.
    type: map
  
pipeline:
  output:
    path: agenticpreprint/biodex/results/extracted_reactions_docetl_aug2024.json
    type: file
  steps:
    - name: synthesized_conditions_extraction
      input: biodex_sample
      operations:
        - synthesized_conditions_extraction

    - name: match_reactions
      operations:
        - match_reactions:
            left: synthesized_conditions_extraction
            right: biodex_terms

    - name: group_reactions
      input: match_reactions
      operations:
        - group_reactions